service: firebase-todo-app

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    FIREBASE_PROJECT: todo-list-e7788

plugins:
  - serverless-offline

custom:
  # Firebase configuration will be handled by environment variables

functions:
  api:
    handler: api/index.handler
    events:
      - http:
          path: /api/{proxy+}
          method: ANY
          cors: true
      - http:
          path: /todos
          method: GET
          cors: true
      - http:
          path: /
          method: GET
          cors: true

  todos:
    handler: functions/todos.handler
    events:
      - http:
          path: /api/todos
          method: GET
          cors: true
      - http:
          path: /api/todos
          method: POST
          cors: true
      - http:
          path: /api/todos/{id}
          method: GET
          cors: true
      - http:
          path: /api/todos/{id}
          method: PUT
          cors: true
      - http:
          path: /api/todos/{id}
          method: DELETE
          cors: true
      - http:
          path: /api/todos/{id}/toggle
          method: PATCH
          cors: true



package:
  patterns:
    - '!node_modules/**'
    - '!storage/logs/**'
    - '!tests/**'
    - '!vendor/**'
    - '!.git/**'
    - '!.env*'
    - '!composer.lock'
    - '!package-lock.json'
    - '!serverless.yml'
    - '!FIREBASE_SETUP.md'
    - '!README.md'
